"""remove group

Revision ID: 9010f8067e63
Revises: 9849f980237a
Create Date: 2020-07-23 15:14:42.847316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9010f8067e63'
down_revision = '9849f980237a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ihome_village', 'group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihome_village', sa.Column('group', mysql.VARCHAR(length=32), nullable=True))
    # ### end Alembic commands ###
