"""empty message

Revision ID: 9849f980237a
Revises: b5d0e9d8fd9d
Create Date: 2020-07-23 13:59:07.524351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9849f980237a'
down_revision = 'b5d0e9d8fd9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihome_factory', sa.Column('area_id', sa.Integer(), nullable=False))
    op.add_column('ihome_factory', sa.Column('city_id', sa.Integer(), nullable=False))
    op.add_column('ihome_factory', sa.Column('street_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ihome_factory', 'ihome_city', ['city_id'], ['id'])
    op.create_foreign_key(None, 'ihome_factory', 'ihome_street', ['street_id'], ['id'])
    op.create_foreign_key(None, 'ihome_factory', 'ihome_area', ['area_id'], ['id'])
    op.drop_column('ihome_factory', 'pay_period')
    op.drop_column('ihome_factory', 'min_months')
    op.drop_column('ihome_factory', 'sale_type')
    op.drop_column('ihome_factory', 'deposit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihome_factory', sa.Column('deposit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('ihome_factory', sa.Column('sale_type', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('ihome_factory', sa.Column('min_months', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('ihome_factory', sa.Column('pay_period', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ihome_factory', type_='foreignkey')
    op.drop_constraint(None, 'ihome_factory', type_='foreignkey')
    op.drop_constraint(None, 'ihome_factory', type_='foreignkey')
    op.drop_column('ihome_factory', 'street_id')
    op.drop_column('ihome_factory', 'city_id')
    op.drop_column('ihome_factory', 'area_id')
    # ### end Alembic commands ###
