"""empty message

Revision ID: ff4e585717e9
Revises: 104ca6de4a2f
Create Date: 2020-07-24 13:32:17.271180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff4e585717e9'
down_revision = '104ca6de4a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihome_factory_facility', sa.Column('facility_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ihome_factory_facility', 'ihome_facility', ['facility_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ihome_factory_facility', type_='foreignkey')
    op.drop_column('ihome_factory_facility', 'facility_id')
    # ### end Alembic commands ###
