"""remove facility2

Revision ID: 104ca6de4a2f
Revises: 9010f8067e63
Create Date: 2020-07-24 13:31:45.208533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '104ca6de4a2f'
down_revision = '9010f8067e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ihome_facility2')
    op.drop_column('ihome_factory_facility', 'facility2_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihome_factory_facility', sa.Column('facility2_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_table('ihome_facility2',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('css', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
