"""empty message

Revision ID: 329b248ddc9b
Revises: df7374194907
Create Date: 2020-07-24 22:20:45.308440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '329b248ddc9b'
down_revision = 'df7374194907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihome_house', sa.Column('area_id', sa.Integer(), nullable=False))
    op.drop_constraint('ihome_house_ibfk_2', 'ihome_house', type_='foreignkey')
    op.create_foreign_key(None, 'ihome_house', 'ihome_area', ['area_id'], ['id'])
    op.drop_column('ihome_house', 'village_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihome_house', sa.Column('village_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ihome_house', type_='foreignkey')
    op.create_foreign_key('ihome_house_ibfk_2', 'ihome_house', 'ihome_village', ['village_id'], ['id'])
    op.drop_column('ihome_house', 'area_id')
    # ### end Alembic commands ###
